### ISSUE TITLE
Docker run on a running Meteor container

### ISSUE THREAD

**Issue by JeromeVi** [apocas/dockerode#378]
Hi,
I need to run a command with Docker run on my container who is a Meteor application.

```
docker.run('gitlab-lab:5005/dfc/mgmt-docker-gui:lab', ['bash', '-c', 'cat docker-compose.yml | docker run -i funkwerk/compose_plantuml --link-graph | docker run -i think/plantuml > output.svg'], [process.stdout, process.stderr], {Tty:false}, function (err, data, container) {
      console.log(data);
      console.error(err);
  });
```

But I get this error:
```
=> Starting meteor app on port:80
/app/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: MONGO_URL must be set in environment
```

My image is builded like this:
```
FROM martinezko/alpine-meteor:latest


RUN mkdir -p /etc/docker/certs.d/gitlab-{lab,int,prod}:5005

ADD http://repos.dfc.local/docker/certs/gitlab-lab.crt /etc/docker/certs.d/gitlab-lab:5005/ca.crt

ENV NODE_ENV=lab

RUN apk add --update curl && \
    rm -rf /var/cache/apk/*

RUN curl -L https://github.com/docker/machine/releases/download/v0.9.0/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine && \
chmod +x /usr/local/bin/docker-machine
```

But this container (mgmt-app) can be started with a `docker-compose up -d` like this :
 ```
 mgmt-app:
    image: gitlab-lab:5005/dfc/mgmt-docker-gui:latest
    container_name: mgmt-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker:/root/.docker
      - /home/dockeradm/compose/area:/home/dockeradm/compose/area
    environment:
      - ROOT_URL=http://localhost:80
      - MONGO_URL=mongodb://mgmt-mongo:27017/meteor
    ports:
      - 80:80
    restart: always
```

So what am I doing wrong ?
